---
- name: include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: ensure latest sudo is installed
  package:    
    name: "{{ init_ansible_mgmt_sudo_package_name }}"
    state: latest

- name: ensure admin group exists
  group:
    name: "{{ init_ansible_mgmt_sudo_group_name }}"
    state: present

- name: give admin group passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ init_ansible_mgmt_sudo_group_name }}"
    line: '%{{ init_ansible_mgmt_sudo_group_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: create ansible user
  user:
    name: "{{ init_ansible_mgmt_user }}"
    state: present
    groups: "{{ init_ansible_mgmt_sudo_group_name }}"
    append: true
    create_home: true
    shell: /bin/bash

- name: copy ansible user ssh key
  authorized_key:
    user: "{{ init_ansible_mgmt_user }}"
    state: present
    key: "{{ init_ansible_mgmt_public_key }}"

- name: disable password authentication for root ssh
  lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'

- name: restart ssh service
  service:
    name: sshd
    state: restarted
    