---
- hosts: proxmox
  gather_facts: true

  vars:
    pve_no_subscription_repo: "deb http://download.proxmox.com/debian/pve buster pve-no-subscription"
    pve_subscription_repo: "deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise"
    pip_install_packages:
      - name: proxmoxer
      - name: request

  pre_tasks:
    - name: remove subscription based repo
      apt_repository:
        repo: "{{ pve_subscription_repo }}"
        state: absent
        filename: pve-enterprise

    - name: add non-subscription based repo
      apt_repository:
        repo: "{{ pve_no_subscription_repo }}"
        state: present

  roles:
    - geerlingguy.pip
    - ironicbadger.ansible_role_proxmox_nag_removal
    - init_ansible
