---
- hosts: proxmox
  remote_user: ansible

  vars:
    pve_deploy_api_passwd: '%'
    pve_deploy_ostemplate: "iso:vztmpl/debian-10-custom_amd64.tar.gz"
    pve_deploy_storage: "vmstore"
    pve_deploy_name: "squeeze"
    pve_deploy_root_passwd: "milk56"
    pve_deploy_container: false
    pve_deploy_vm_clone: "Debian10Template"

  roles:
    - pve_deploy
    
#   post_tasks:

#     - name: add new ct to inventory
#       add_host:
#         hostname: "{{ pve_deploy_name }}"
#         groups: new_ct
#         ansible_user: "root"
#         ansible_ssh_pass: "%"

#     - name: wait for ssh to start
#       wait_for:
#         host: "{{ pve_deploy_name }}"
#         port: 22
#         delay: 5

# - hosts: new_ct
  
#   tasks:

#     - name: just a test
#       shell: ls /etc
#       register: output

#     - debug:
#         msg: "{{ output }}"

