init_packages: ['sudo', 'vim', 'git', 'ufw']
init_enabled_repos: 
  - deb http://ftp.us.debian.org/debian buster main contrib non-free
  - deb http://security.debian.org/debian-security buster/updates main contrib
  - deb-src http://ftp.us.debian.org/debian buster main contrib non-free
  - deb-src http://security.debian.org/debian-security buster/updates main contrib