---
- name: install required packages
  package:
    name: "{{ shinobi_role_required_packages }}"
    state: present

- name: clone shinobi repo
  git:
    repo: "{{ shinobi_role_git_repo }}"
    dest: "{{ shinobi_role_install_dir }}"
    clone: true # true is default
    update: true # true is default
    version: "{{ shinobi_role_repo_version }}"

- name: copy super user creds
  template: 
    dest: "{{ shinobi_role_install_dir }}/super.json"
    src: super.json.j2

- name: copy config
  template: 
    dest: "{{ shinobi_role_install_dir }}/conf.json"
    src: conf.json.j2

- name: start shinobi camera
  command: pm2 start camera.js
  args:
    chdir: "{{ shinobi_role_install_dir }}"
  changed_when: false

- name: start shinobi cron
  command: pm2 start cron.js
  args:
    chdir: "{{ shinobi_role_install_dir }}"

- name: save shinobi processes
  command: pm2 save
  args:
    chdir: "{{ shinobi_role_install_dir }}"

- name: enable shinobi startup at boot
  command: pm2 startup
  args:
    chdir: "{{ shinobi_role_install_dir }}"