---
- proxmox:
    node: "{{ pve_ct_node }}"
    api_host: "{{ pve_ct_api_host }}"
    api_user: "{{ pve_ct_api_user }}"
    api_password: "{{ pve_ct_api_passwd }}"
    hostname: "{{ pve_ct_hostname }}"
    ostemplate: "{{ pve_ct_ostemplate }}"
    pubkey: "{{ pve_ct_public_key | default(omit) }}"
    password: "{{ pve_ct_root_passwd }}"
