---
- name: disable cdrom repo
  replace:
    path: /etc/apt/sources.list
    regexp: '(.*cdrom.*)'
    replace: '#\1'

- name: enable repos
  apt_repository:
    repo: "{{ item }}" 
    state: present
  loop: "{{ init_enabled_repos }}"

- name: install initial packages
  apt: 
    name: "{{ init_packages }}"
    update_cache: yes
    state: latest