---
docker_pihole_network: "pihole-net"
docker_pihole_subnet: "10.3.20.0/24"
docker_pihole_ip: "10.3.20.20"
docker_pihole_dns1: "8.8.8.8"
docker_pihole_dns2: "9.9.9.9"
docker_pihole_web_password: "badpass01"
docker_pihole_timezone: "America/New_York"
docker_pihole_hostname: "{{ inventory_hostname }}"
docker_pihole_image_version: "latest"
docker_pihole_volume_base: "/opt/docker-volumes"
docker_pihole_volume_path: "{{ docker_pihole_volume_base }}/pihole"
