---

- name: add vfio modules to /etc/modules
  lineinfile:
    path: /etc/modules
    line: '{{ item }}'
    create: true
  loop: '{{ pve_enable_passthru_vfio_modules }}'
  notify:
    - reboot pve

# https://pve.proxmox.com/wiki/Pci_passthrough Nvidia tips
- name: ignore msrs
  lineinfile:
    path: '{{ pve_enable_passthru_module_options_path }}'
    line: 'options kvm ignore_msrs=1'
    create: true
  when: pve_enable_passthru_ignore_msrs
  notify: 
    - reboot pve

# https://pve.proxmox.com/wiki/PCI(e)_Passthrough Finish Configuration
- name: allow unsafe interrupts
  lineinfile: 
    path: '{{ pve_enable_passthru_module_options_path }}'
    line: 'options vfio_iommu_type1 allow_unsafe_interrupts=1'
    create: true
  when: pve_enable_passthru_allow_unsafe_interrupts
