---
- hosts: pihole
  gather_facts: true

  roles:
    - role: zfuller.pihole
      pihole_setupvars_ipv4_address: 192.168.1.3
      pihole_setupvars_webpasswd:
      pihole_setupvars_pihole_dns_1: 208.67.222.222 # OpenDNS
      pihole_setupvars_pihole_dns_2: 208.67.220.220 # OpenDNS
