---
- hosts: windows

  tasks:
    - debug:
        msg: "doing something"

    - name: install packages
      win_chocolatey:
        name:
          - 7zip
          - cinebench
          - cpu-z
          - cura-new
          - Firefox
          - git
          - GoogleChrome
          - gpu-z
          - msiafterburner
          - mysql.workbench
          - notepadplusplus
          - opera
          - putty
          - steam
          - vcredist140
          - vcredist2010
          - vcredist2012
          - vcredist2013
          - vcredist2015
          - vmrc
          - vscode
      tags: 
        - software

    - name: install nvidia stuff
      win_chocolatey:
        name: 
          - nvidia-display-driver
          - geforce-experience
      tags:
        - nvidia

