---
- hosts: windows

  tasks:

    - name: install packages
      win_chocolatey:
        name:
          - 7zip
          - cpu-z
          - cura-new
          - Firefox
          - git
          - GoogleChrome
          - gpu-z
          - msiafterburner
          - mysql.workbench
          - notepadplusplus
          - opera
          - putty
          - vcredist140
          - vcredist2010
          - vcredist2012
          - vcredist2013
          - vcredist2015
          - vmrc
          - vscode
      tags: 
        - software

    - name: install gaming stuff
      win_chocolatey:
        name:
          - steam
          - origin
          - uplay
      tags:
        - gaming

    - name: install benchmarks
      win_chocolatey:
        name:
          - cinebench
          - heaven-benchmark
          - superposition-benchmark
          - valley-benchmark
      tags:
        - benchmarks

    - name: install nvidia stuff
      win_chocolatey:
        name: 
          - nvidia-display-driver
          - geforce-experience
      tags:
        - nvidia

